server:
  port: 8081

spring:
  application:
    name: user-microsservice
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-user
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: 
broker:
   queue:
      email:
         name: default.email