server:
  port: 8080
spring:
  application:
    name: email-microsservice
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiagopereiraast@gmail.com
    password:
    properties:
       mail:
          smtp:
             auth: true
             starttls:
               enable: true
broker:
   queue:
      email:
         name: default.email
         